-- P16 (suite) - extension du moteur d'automatisation P11 (nouveaux
-- déclencheurs mission/portail DO/RDV) - additif uniquement, réutilise
-- exactement AutomationRule/AutomationExecution/EmailDraft/EmailSendLog/
-- Notification déjà existants (jamais un second moteur).

ALTER TABLE `AutomationRule` MODIFY COLUMN `triggerType` ENUM('DOSSIER_STATUS_CHANGED', 'WORKFLOW_STEP_READY', 'WORKFLOW_STEP_LATE', 'DOCUMENT_MISSING', 'DOCUMENT_REJECTED', 'DOCUMENT_EXPIRED', 'TRANSMISSION_READY', 'LEAD_STATUS_CHANGED', 'LEAD_CALLBACK_DUE', 'APPOINTMENT_UPCOMING', 'FINANCIAL_PAYMENT_DUE', 'FINANCIAL_PAYMENT_LATE', 'CEE_READY', 'ANAH_STATUS_CHANGED', 'STUDY_STALE', 'MANUAL_TRIGGER', 'MISSION_ST_CREEE', 'MISSION_ST_ACCEPTEE', 'MISSION_ST_REFUSEE', 'MISSION_CHANTIER_PROGRAMME', 'MISSION_DATE_MODIFIEE', 'MISSION_TERMINEE', 'DO_DEMANDE_RECUE', 'DO_COMPLEMENT_REQUIS', 'DO_COMPLEMENT_RECU', 'DO_CHANTIER_ACCEPTE', 'DO_CHANTIER_PROGRAMME', 'DO_CHANTIER_TERMINE', 'DO_FACTURE_DISPONIBLE', 'REGIE_NOUVEAU_LEAD', 'RDV_CREE', 'RDV_MODIFIE_OU_ANNULE') NOT NULL;

ALTER TABLE `TransmissionPackage` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Dossier`
    ADD COLUMN `complementDemandeMessage` VARCHAR(191) NULL,
    ADD COLUMN `complementReponseMessage` VARCHAR(191) NULL,
    ADD COLUMN `complementDemandeAt` DATETIME(3) NULL,
    ADD COLUMN `complementReponseAt` DATETIME(3) NULL;
